### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rtdavis22** [actions-rust-lang/audit#17]
Hello, I'm getting the following error:
```
Received 0 of 3589271 (0.0%), 0.0 MBs/sec
Received 3589271 of 3589271 (100.0%), 3.3 MBs/sec
Cache Size: ~3 MB (3589271 B)
/usr/bin/tar --use-compress-program unzstd -xf /home/runner/work/_temp/763078f7-6abf-480e-99a0-976057797b44/cache.tzst -P -C /home/runner/work/oneschema/oneschema
Cache restored successfully
Cache restored from key: cargo-audit-v0.17.4
Run import audit
1 entries found.
Traceback (most recent call last):
  File "/home/runner/work/_temp/8d9d485b-a9c7-4c6a-8685-a302dcff39aa.py", line 2, in <module>
    audit.run()
  File "/home/runner/work/_actions/actions-rust-lang/audit/v1/audit.py", line [34](https://github.com/oneschema/oneschema/actions/runs/3745287106/jobs/6360913737#step:3:38)2, in run
    step_summary.write(entry.format_as_markdown())
  File "/home/runner/work/_actions/actions-rust-lang/audit/v1/audit.py", line 1[37](https://github.com/oneschema/oneschema/actions/runs/3745287106/jobs/6360913737#step:3:41), in format_as_markdown
    entry_table = self._entry_table()
  File "/home/runner/work/_actions/actions-rust-lang/audit/v1/audit.py", line 68, in _entry_table
    table.append(("Package", f"`{advisory['package']}`"))
TypeError: 'NoneType' object is not subscriptable
```

My workflow looks like this:
```
name: "Audit Dependencies"
on:
  push:
    paths:
      # Run if this workflow file changes
      - ".github/workflows/audit.yml"
      # Run on changed dependencies
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
        with:
          ignore: RUSTSEC-2020-0071,RUSTSEC-2021-0139
          createIssues: false
```

Am I doing something incorrect?

**Comment by jonasbb** [comment]
Hi, thanks for the report. The repository is "oneschema/oneschema", right? That seems to be a private repository, so it is hard for me to debug right now. There is nothing obviously wrong which I can see. 

Is there anything special about the oneschema repository? Could you please also post the output of `cargo audit --json --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2021-0139` when run in the root of the repository.

I will add some debug and robustness improvements to improve the situation in the future.

**Comment by rtdavis22** [comment]
@jonasbb Yes, it's a private repo. Here's the output:
```
oneschema $ cargo audit --json --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2021-0139 | jq .
{
  "database": {
    "advisory-count": 474,
    "last-commit": "2addcf11333a29d9339fbbffd5e97aca293aeaa2",
    "last-updated": "2022-12-18T12:08:00Z"
  },
  "lockfile": {
    "dependency-count": 492
  },
  "settings": {
    "target_arch": null,
    "target_os": null,
    "severity": null,
    "ignore": [
      "RUSTSEC-2020-0071",
      "RUSTSEC-2021-0139"
    ],
    "informational_warnings": [
      "unmaintained"
    ]
  },
  "vulnerabilities": {
    "found": false,
    "count": 0,
    "list": []
  },
  "warnings": {
    "yanked": [
      {
        "kind": "yanked",
        "package": {
          "name": "openssl",
          "version": "0.10.44",
          "source": "registry+https://github.com/rust-lang/crates.io-index",
          "checksum": "29d971fd5722fec23977260f6e81aa67d2f22cadbdc2aa049f1022d9a3be1566",
          "dependencies": [
            {
              "name": "bitflags",
              "version": "1.3.2",
              "source": "registry+https://github.com/rust-lang/crates.io-index"
            },
            {
              "name": "cfg-if",
              "version": "1.0.0",
              "source": "registry+https://github.com/rust-lang/crates.io-index"
            },
            {
              "name": "foreign-types",
              "version": "0.3.2",
              "source": "registry+https://github.com/rust-lang/crates.io-index"
            },
            {
              "name": "libc",
              "version": "0.2.138",
              "source": "registry+https://github.com/rust-lang/crates.io-index"
            },
            {
              "name": "once_cell",
              "version": "1.16.0",
              "source": "registry+https://github.com/rust-lang/crates.io-index"
            },
            {
              "name": "openssl-macros",
              "version": "0.1.0",
              "source": "registry+https://github.com/rust-lang/crates.io-index"
            },
            {
              "name": "openssl-sys",
              "version": "0.9.79",
              "source": "registry+https://github.com/rust-lang/crates.io-index"
            }
          ],
          "replace": null
        },
        "advisory": null,
        "versions": null
      }
    ]
  }
}
```
Is it caused by `advisory` being `null`?

**Comment by jonasbb** [comment]
Thank you, that is very helpful. So the issue is around yanked crates, which don't have an advisory associated with it. I will improve the situation.

**Comment by jonasbb** [comment]
I released a new version v.1.1.4 which should no longer fail. Instead it shows a message that the crate is yanked.

**Comment by rtdavis22** [comment]
Thanks, @jonasbb! I
